# Generated by Django 5.0.7 on 2024-07-17 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consignataria', '0001_initial'),
        ('servidor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaMargemAthenas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margem_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem_disponivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consignataria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consignataria.consignataria')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor')),
            ],
        ),
    ]
